status = [
        {"name": "FreeBSD-head-riscv64-build", "status": "undefined"},
        {"name": "FreeBSD-head-sparc64-build", "status": "undefined"},
        {"name": "FreeBSD-head-powerpc64-build", "status": "undefined"},
        {"name": "FreeBSD-head-powerpc-build", "status": "undefined"},
        {"name": "FreeBSD-head-mips64-build", "status": "undefined"},
        {"name": "FreeBSD-head-mips-build", "status": "undefined"},
        {"name": "FreeBSD-head-i386-build", "status": "undefined"},
        {"name": "FreeBSD-head-armv6-build", "status": "undefined"},
        {"name": "FreeBSD-head-aarch64-build", "status": "undefined"},
        {"name": "FreeBSD-head-amd64-build", "status": "undefined"},

        {"name": "FreeBSD-stable-11-amd64-build", "status": "undefined"},
        {"name": "FreeBSD-stable-11-aarch64-build", "status": "undefined"},
        {"name": "FreeBSD-stable-11-armv6-build", "status": "undefined"},
        {"name": "FreeBSD-stable-11-i386-build", "status": "undefined"},
        {"name": "FreeBSD-stable-11-mips-build", "status": "undefined"},
        {"name": "FreeBSD-stable-11-mips64-build", "status": "undefined"},
        {"name": "FreeBSD-stable-11-powerpc-build", "status": "undefined"},
        {"name": "FreeBSD-stable-11-powerpc64-build", "status": "undefined"},
        {"name": "FreeBSD-stable-11-sparc64-build", "status": "undefined"},
        {"name": "FreeBSD-stable-11-riscv64-build", "status": "undefined"},

        {"name": "FreeBSD-stable-10-riscv64-build", "status": "undefined"},
        {"name": "FreeBSD-stable-10-sparc64-build", "status": "undefined"},
        {"name": "FreeBSD-stable-10-powerpc64-build", "status": "undefined"},
        {"name": "FreeBSD-stable-10-powerpc-build", "status": "undefined"},
        {"name": "FreeBSD-stable-10-mips64-build", "status": "undefined"},
        {"name": "FreeBSD-stable-10-mips-build", "status": "undefined"},
        {"name": "FreeBSD-stable-10-i386-build", "status": "undefined"},
        {"name": "FreeBSD-stable-10-armv6-build", "status": "undefined"},
        {"name": "FreeBSD-stable-10-aarch64-build", "status": "undefined"},
        {"name": "FreeBSD-stable-10-amd64-build", "status": "undefined"},

        {"name": "System-up", "status": "undefined"},
        {"name": "Last-update", "status": "undefined"},
        {"name": "null", "status": "undefined"}
        ]
